name: Run cloud-nuke

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight. Adjust as needed.

jobs:
  cloud-nuke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cloud-nuke
        run: |
          curl -LO https://github.com/gruntwork-io/cloud-nuke/releases/download/v0.1.27/cloud-nuke_linux_amd64
          sudo install cloud-nuke_linux_amd64 /usr/local/bin/cloud-nuke

      - name: Run cloud-nuke
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cloud-nuke aws --region us-east-1  # Adjust the region as needed

